# YOUR NAME OR TITLE OF YOUR SITE
name: KanpurFOSS

# YOUR BRAND/PERSONAL TAGLINE
tagline: Kanpur FOSS is a community of open source enthusiasts. We promote free & open internet, and inclusivity. And you, my friend, are invited to be a part of our awesome community! :)

# YOUR/BRAND IMAGE URL
Image_URL: https://i.imgur.com/RDDr9uB.jpeg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: kanpurfoss
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: kanpurfoss
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: kanpurfoss
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: kanpurfoss
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:kanpurfoss@gmail.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # CUSTOM LINK
  - Name: Website
    URL: https://kanpurfoss.org
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown